image: quay.io/librelabs/ci:dind17

before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh

local plugin-test:
  script:
    - asdf plugin-add draft ./
    - asdf list-all draft
    - asdf plugin-test draft ./


remote plugin-test:
  script:
    - asdf plugin-test draft https://gitlab.com/td7x/asdf/draft.git